import React, { useEffect } from 'react';
import './ProductDetail.css';

const ProductDetail = ({ product, onBack, products, onSelectProduct }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [product]);

  if (!product) return null;

  return (
    <div className="product-detail-page">
      <div className="detail-container">
        {/* Back Navigation */}
        <button className="back-btn" onClick={onBack}>
          ← Back to Products
        </button>

        {/* Hero Header */}
        <header className="detail-hero glass-panel">
          <div className="detail-hero-text">
            <span className="detail-badge">Solution #{product.id}</span>
            <h1>{product.name}</h1>
            <p className="detail-lead">{product.details}</p>
            <button className="btn">Get Started with this Solution</button>
          </div>
          <div className="detail-hero-image">
            <img src={product.image} alt={product.alt} />
            <div className="detail-hero-overlay"></div>
          </div>
        </header>

        {/* Main Content + Sidebar Layout */}
        <div className="detail-layout">
          {/* Main Content */}
          <main className="detail-main">
            {/* About Section */}
            <section className="detail-section glass-panel">
              <div className="section-header">
                <div className="section-accent-bar"></div>
                <h2>Solution Overview</h2>
              </div>
              <p>{product.about}</p>
            </section>

            {/* Benefits & Scope Grid */}
            <div className="detail-two-col">
              <div className="detail-section glass-panel detail-benefits-card">
                <h3>Key Benefits &amp; Advantages</h3>
                <ul className="benefits-list">
                  {product.benefits.map((benefit, i) => (
                    <li key={i}>
                      <span className="benefit-check">⚡</span>
                      <span>{benefit}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="detail-section glass-panel detail-scope-card">
                <h3>Vision 2045: Feature Scope</h3>
                <p>{product.futureScope}</p>
              </div>
            </div>

            {/* Integration Section */}
            <section className="detail-section glass-panel detail-integration">
              <h2>Supply Chain Visibility &amp; Optimization Integration</h2>
              <div className="integration-box">
                <p>
                  <strong>{product.name}</strong> is engineered to work in perfect harmony with our core 
                  Supply Chain Visibility and Optimization Software. This integration ensures that 
                  every data point generated by this solution is immediately actionable within the 
                  broader global logistics ecosystem.
                </p>
              </div>
              <div className="integration-note">
                <span className="note-label">Integration Note:</span> {product.integrationNote}
              </div>
            </section>

            {/* Inquire Section */}
            <section className="detail-section glass-panel detail-inquire">
              <h2>Request Product Consultation</h2>
              <p>Connect with our technical architects to see how this solution fits into your specific logistics infrastructure.</p>
              <div className="inquire-contact">
                <span>✉ contact@techbrainnetworks.com</span>
              </div>
              <button className="btn">Submit Secure Inquiry</button>
            </section>
          </main>

          {/* Sidebar */}
          <aside className="detail-sidebar">
            <div className="sidebar-products glass-panel">
              <h3>Our Solutions</h3>
              <div className="sidebar-list">
                {products.map(p => (
                  <div 
                    key={p.id} 
                    className={`sidebar-item ${p.id === product.id ? 'active' : ''}`}
                    onClick={() => onSelectProduct(p.id)}
                  >
                    <span className="sidebar-item-name">{p.name}</span>
                    <span className="sidebar-arrow">›</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="sidebar-cta glass-panel">
              <h4>Need Customization?</h4>
              <p>Our R&amp;D team can tailor any solution to your specific logistics requirements.</p>
              <button className="sidebar-cta-link">Talk to an Engineer →</button>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
};

export default ProductDetail;
